#!/usr/bin/env bash

#-----------------------------------------------------------------------
# testing helper
# Author: Osita Ighodaro
#-----------------------------------------------------------------------

cp=.
for jarfile in ~/lib/sqlite/*.jar ~/lib/spark/*.jar; do
   cp=$cp:$jarfile
done

java -cp $cp "$@"